version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3333:3333
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:8000