name: ESLint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run lint