name: CI
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    name: ESLint
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run lint
  sanity-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v2
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: deploy